<PageLayoutEx>:
    Button:
        text: "Halaman 1"

    Button:
        text: "Halaman 2"
    
    Button:
        text: "Halaman 3"
    
    Button:
        text: "Halaman 4"

    Button:
        text: "Halaman 5"

    Button:
        text: "Halaman 6"

    Button:
        text: "Halaman 7"

    Button:
        text: "Halaman 8"

    Button:
        text: "Halaman 9"

    Button:
        text: "Halaman 10"