<Text_input>:
    title: 'Input Dialog in Kivy'
    auto_dismiss: False
    id: test1

    RelativeLayout:
        orientation: 'vertical'
        pos: self.pos
        size: root.size
        id: test2

        TextInput:
            id: Input
            hint_text: 'Masukkan Text'
            pos_hint: {'center_x': 0.5, 'center_y': 0.705}
            size_hint: 0.95, 0.5
            on_text: app.text_process()