<CustomDropDown>:
    Button:
        text: 'Nama Kampus'
        size_hint_y: None
        height: 44
        on_release: root.select('Kampus adalah')

    Label:
        text: 'Sedang tidak berkuliah'
        size_hint_y: None
        height: 44
    
    Button:
        text: 'Universitas PGRI Madiun'
        size_hint_y: None
        height: 44
        on_release: root.select('Universitas PGRI Madiun')