<CarouselLayout>:
    rows: 2

    Label:
        text: str(id(root))

    Button:
        text: 'Load(page 3)'
        on_release:
            carousel = root.parent.parent
            carousel.load_slide(carousel.slides[2])

    Button:
        text: 'Sebelumnya'
        on_release: root.parent.parent.load_previous()

    Button:
        text: 'Selanjutnya'
        on_release: root.parent.parent.load_next()