# Membuat sebuah label dengan text hello world
# dengan ukuran font 60 dp
# dp adalah Density-independent Pixels
# sehingga ukuran font berdasarkan dari besar pixel perangkat
Label:
    text:
        ('[b]Hello[/b] [color=ff0099]World[/color]\n'
        '[color=ff0099]Hello[/color] [b]World[/b]\n'
        '[b]Hello[/b] [color=ff0099]World:):)[/color]')
    markup: True
    font_size: dp(60)